### ISSUE TITLE
Error at server side while clicking on report in menu

### ISSUE THREAD

**Issue by ankurdotcom** [gtmsoftware/fleet-wise#5]
Error at server side while clicking on report in menu and application stop working

`/home/ec2-user/fleet-wise/routes/report.js:19
  for(let i = 0; i < dataList.length; i++) {
                              ^

TypeError: Cannot read properties of undefined (reading 'length')
    at getTotalCollection (/home/ec2-user/fleet-wise/routes/report.js:19:31)
    at /home/ec2-user/fleet-wise/routes/report.js:69:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
`

**Comment by dev-ambar** [comment]
@gtmsoftware  please assign me this issue

**Comment by gtmsoftware** [comment]
ok @dev-ambar   its assigned to you.
